# Code counting using scc

name: Liczenie ilości linii kodu

on:
  push:
     branches: [master]

jobs:
   codelinecount:
    runs-on: ubuntu-latest
    name: CCR
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Count
        id: scc
        uses: Adapt-API/scc-docker-action@master
        with:
          args: ${{ env.workspace }} -i h,cpp,inl,hpp,c,cc,ino,sh,glsl,js,css,html,java,svelte,asm --exclude-dir .idea,.vscode,.github,target
      - name: Output
        run: |
          echo
          echo -n "${{ steps.scc.outputs.scc }}"
